### ISSUE TITLE
PO007 is missing indications for "remove" element

### ISSUE THREAD

**Issue by endemics** [apigee/apigeelint#124]
The list of indications for ["AssignMessage"](https://github.com/apigeecs/bundle-linter/blob/master/lib/package/plugins/policyNameConventions.js#L17) does not contain any indication suitable for the ["remove" element ](https://docs.apigee.com/api-platform/reference/policies/assign-message-policy#removeelement).

Suitable indications could be:
- "remove"
- "strip"
- "delete"

**Comment by kurtkanaskie** [comment]
@endemics Check out the new feature to provide a path to externalPlugins and the example in the same directory in this repo, which shows how to use the feature and provide you our indications.

**Comment by DinoChiesa** [comment]
As Kurt explained, you can modify the prefixes as you wish.

We think "AM" is a good prefix. If you're using it to remove headers, then AM-RemoveHeaders is a nice pattern.
That's why the PO007 works the way it does. 

If you don't like that you can disable the PO007 plugin and write your own with your own prefixes.
