### ISSUE TITLE
ExternalPlugins not working anymore with 2.1.0

### ISSUE THREAD

**Issue by RomanKreisel** [apigee/apigeelint#217]
Previously created plugins return "For plugin file C, bad plugin filename format"

This also happens with the example in [https://github.com/apigee/apigeelint/blob/master/externalPlugins/EX-PO007-NamingConventions.js](url)

Can you please provide an example on how external plugins should look like now? Not sure if I have to invoke myUtil.sh from my external plugin - and if so, how to do that.

**Comment by kurtkanaskie** [comment]
This is due to an internal change to rename the plugins to reflect the rule Id and to get the rule Id from the filename directly.
The code expects a format like "XX###-wordsGoHere.js".
So to get around this situation, name your external plugins using that naming convention, e.g. EX007-NamingConventions.js

**Comment by kurtkanaskie** [comment]
Hmmm, further testing of the provided example external plugin does not cause a filename error. 
The plugin file naming conventions only apply if the plugin calls the helper function. 
See https://github.com/apigee/apigeelint/tree/master/lib/package/plugins
So you can just set the ruleId directly in your plugin as the example shows.

**Comment by ssvaidyanathan** [comment]
v2.1.1 released and should have the fix
