### ISSUE TITLE
apigeelint return codes (0 or 1) to use it in GitLab CI

### ISSUE THREAD

**Issue by jhd235** [apigee/apigeelint#260]
apigeelint return codes (0 or 1) to use it in GitLab CI.
is there already capability of the apigeelint to return 0 if no errors/warnings?
such a feature could be useful to tell the CI job status of failure or success.
thanks a lot, Yermek

**Comment by ssvaidyanathan** [comment]
@jhd235 
Yes it does. Please check [here](https://github.com/apigee/apigeelint/blob/58d499d3ac1eb7668340f2b065d122df9f1484de/lib/package/bundleLinter.js#L130).

We have this plugin used within pipeline and it breaks the pipeline and marks it as failed due to the return codes. 

If this answers your question, please close the issue

**Comment by jhd235** [comment]
Thank you @ssvaidyanathan . I'm closing the issue as a resolved.
